### ISSUE TITLE
auto cleanup of temporary track files 

### ISSUE THREAD

**Issue by paul-shannon** [gladkia/igvShiny#25]
@chikao0817 asked this question.
This arises from the design of igvShiny:
- igv.js primarily loads track data from a url, a web server
- we typically deal in direct data, often R data.frames, in igvShiny and igvR
- ```displayTrack``` writes files (often bed files) to a local directory  visible to the small webserver embedded in igvShiny
- it should be safe to delete these files as soon as igv.js has displayed them
- though large region files, larger than the current visibility window, may need to persist.
I will be looking at this further, and soon.

**Comment by gladkia** [comment]
Solved with https://github.com/gladkia/igvShiny/pull/60.
