### ISSUE TITLE
ThickStart/End, TrackHeight of original track, etc.

### ISSUE THREAD

**Issue by bmktornado** [gladkia/igvShiny#52]
Really a huge fan of what you have created here. I have stumbled on this package hours after your recent commit, and have some notes from a first user of new functionality:

- thickStart/thickEnd capability from BED files. Can't find a way to change the width of tracks like this. Is this implemented yet?
- trackHeight of original RefSeq track. I see your note in the code about this being a to-do, just upping the importance of it.
- The folder 'tracks' caused some hiccups, especially when deploying from the folder after I've done testing of the app locally. Shiny is trying to automatically deploy this folder, not sure if that's intended.
- When I upload a GFF3 track from a URL, it takes the track name from that URL, rather than the trackName specified in the call to add the track, and the parameter 'trackName'. This is causing issues downstream because if I want to remove the track, the remove track function is, I believe, calling the trackName title, not the URL. So the remove track function doesn't work, but it does with the name drawn from the URL.

Nonetheless, great work. Will continue to forward some bugs when I find them.

**Comment by gladkia** [comment]
Hi @bmktornado. 

Thanks for the great feedback! 

I've just improved the logic for handling the tracks (https://github.com/gladkia/igvShiny/pull/60).

Can you please prepare some reprexes ([link](https://community.rstudio.com/t/faq-whats-a-reproducible-example-reprex-and-how-do-i-create-one/5219)) for the remaining suggestions? This will help me a lot to work on them (1) and this will make the final solution potentially more robust (2) as I might be able to use your reprexes for the unit testing. Thanks in advance.

**Comment by gladkia** [comment]
@bmktornado, the issue with trackName' not being removed via the remove track function has been fixed (https://github.com/gladkia/igvShiny/pull/73). 
Thanks again for your help.
