### ISSUE TITLE
Parameterize "tracks" directory

### ISSUE THREAD

**Issue by j-andrews7** [gladkia/igvShiny#54]
As noted here:
https://github.com/gladkia/igvShiny/blob/master/R/igvShiny.R#L79

This would allow the use of tmp directories and seamless cleanup by apps.

**Comment by gladkia** [comment]
Hi @j-andrews7, the feature has been added. 

You can now set the directory for tracks with environmental variable:
```
Sys.setenv(TRACKS_DIR = "/path/to/tracks"
```
Then you have to restart the sesion on reload the package, e.g. with:
```
pkgload::load_all("~/path/to/pkg/code")
```

Here are the key parts of the logic:
- https://github.com/gladkia/igvShiny/blob/master/R/zzz.R
- https://github.com/gladkia/igvShiny/blob/master/R/utils.R#L19
As you can see for most users there will be no need to define an environmental variable. Under such circumstances,  the default path will be used. The default path is the subdirectory in the tempdir. Thus the data will be eventually cleaned.
