### ISSUE TITLE
loadBamTrackFromLocalData produces errors with local tumor.bam

### ISSUE THREAD

**Issue by yelekley** [gladkia/igvShiny#71]
Hello,
I'm testing /inst/demos/igvShinyDemo.R with tumor.bam you've provided, however, I get the following error followed by a crash of the application. I can see that the file loaded since:
x <- readGAlignments(bamFile)
  print(head(x))
returns lines from bam, so it's able to load the file.  There must be a problem with loadBamTrackFromLocalData?
`Error in as.character: cannot coerce type 'closure' to vector of type 'character'`
I've tried my own local bam file and got the same result.
Thank you for your help.

**Comment by gladkia** [comment]
Hi @yelekley,

Thanks for the detailed info. @karollayna has just fixed the issue (https://github.com/gladkia/igvShiny/pull/70). 
Please use the latest master. Also, the latest version will be available on Bioconductor DEV (3.19) within the next few days.
