### ISSUE TITLE
When ivgshiny starts up, initialize certain tracks.

### ISSUE THREAD

**Issue by jmzhang1911** [gladkia/igvShiny#75]
Hello developer,

Greetings! Thank you for developing such an intriguing tool. I encountered an issue while using it: How can I import some tracks during initialization? I noticed that igvShiny includes a parameter called tracks, but I'm unsure how to specify it.

For instance, I have a track that can be loaded and displayed using loadBedGraphTrack(session = session, id = 'igvShiny', trackName = 'DPC_EP_1', tbl = tbl.bed5, autoscale = TRUE, color = "blue"). My aim is to display this track when igvShiny starts.

Looking forward to your reply. Best regards!

**Comment by gladkia** [comment]
Hi @jmzhang1911,

Thanks for your kind words. 

You have to create the Shiny app and then define your BED track there. Please take a look at the package overview: [link](https://gladkia.github.io/igvShiny/articles/igvShiny.html) to familiarize yourself with the general concept. 
You don't have to create the app from scratch. You can reuse the demo app. In your case updating [this line](https://github.com/gladkia/igvShiny/blob/master/inst/demos/igvShinyDemo.R#L89) with your data should be enough. Then run the demo app with:

```
demo_app_file <- "/your/path/to/modifiyed/igvShinyDemo.R"
shiny::[runApp](https://rdrr.io/pkg/shiny/man/runApp.html)(demo_app_file)
```
