### ISSUE TITLE
Problem running with local files

### ISSUE THREAD

**Issue by BELKHIR** [gladkia/igvShiny#76]
Hi,

I'm trying to run the demo example with data (genome and annotation) provided from local files following this code as  in the vignette:   

library(igvShiny)
demo_app_file <-
    system.file(
        package = "igvShiny", 
        "demos", 
        "igvShinyDemo-customGenome-localFiles.R")
if (interactive()) {
    shiny::runApp(demo_app_file)
    } 

The shiny app opens in the browser but the selectinput beside the IGV icon is empty, so no way to select any contig.
I tried this code from an R console and from Rstudio without success.

However the demo app works fine.

Any idea ?

Many thanks,

**Comment by gladkia** [comment]
Hi @BELKHIR,

Thanks for your interest in `igvShiny`.

Good catch! You've identified the regression affecting the support for custom genomes. All demo apps with custom genomes do not work properly ([link1](https://github.com/gladkia/igvShiny/tree/master/inst/demos/customGenomes), [link2](https://github.com/gladkia/igvShiny/blob/master/inst/demos/igvShinyDemo-customGenome-localFiles.R), [link3](https://github.com/gladkia/igvShiny/blob/master/inst/demos/igvShinyDemo-customGenome-http.R)).

I've started working on it. I'll keep you updated.
