### ISSUE TITLE
VCF File Not Found When Running igvShinyDemo-withVCF.R

### ISSUE THREAD

**Issue by almreis** [gladkia/igvShiny#78]
First, I would like to thank the developers for their excellent work on igvShiny. It has worked really well for me in the past. I am currently trying to implement my app on a new server, running igvShiny from within an on demand RStudio app. When running the igvShinyDemo-withVCF.R script, I encounter an error indicating that the VCF file could not be found, with the URL to the tmp.vcf file being printed. However, the igvShinyDemo-withModules.R script works perfectly fine. I would like to understand how the function to load VCF files differs from the function to load BAM files, because it looks like the tmp.vcf cannot be found by built-in igvShiny server. Any help would be greatly appreciated!

Environment
R version: 4.3.1
igvShiny version: 0.99.7
Operating System: Linux

**Comment by gladkia** [comment]
Hi @almreis, sorry for the late response. 

I've just fixed the issue (with the 1.0.2 version). Please use the latest master branch. 
The version with the fixes will be available on Bioc `3.19` and Bioc `devel` within the next few days.
