### ISSUE TITLE
loadBedTrack fails when app is launched with query strings

### ISSUE THREAD

**Issue by parv-sachdeva** [gladkia/igvShiny#88]
Hello!

I am running my shiny app with query strings for variables (e.g. `localhost/?dataset=<dataset_name>`). 

The loadBedTrack function tries to capture the webpage url and appends the file track url to it which results in a malformed url such as `localhost/?dataset=<dataset_name>tracks/tracks.bed`. The app then tries to parse the webpage html and this results in a `Unparsable bed record` error.

This leads to an incorrect track load and an empty track added to the html widget.

Error on the console:
![image](https://github.com/user-attachments/assets/481462af-b97b-40c1-8e65-593875eae106)

I will create a pull request with the fixes, for now I am using a locally modified copy.

Best Regards,
Parv Sachdeva

**Comment by gladkia** [comment]
Hi @parv-sachdeva,

Thanks for detailed explanation as well as the help in the form of PR :)! 
I've triggered the builds. Please bump the version in the DESCRIPTION and add info in news.md and I will approve.
Thanks again.

**Comment by parv-sachdeva** [comment]
Hi @gladkia 

I have updated the version to v1.0.5 and also updated NEWS.md with the info.

Best,
Parv
