### ISSUE TITLE
Error: Unknown genome id: hg19

### ISSUE THREAD

**Issue by heimannch** [gladkia/igvShiny#90]
I have an Shiny app that uses the hg19 genome assembly in igvShiny (`genomeOptions <- igvShiny::parseAndValidateGenomeSpec(genomeName="hg19",  initialLocus="all")`), but I started to get an error message in the app that says: "Unknown genome id: hg19". I get no additional error or message in the console. I also updated the igvShiny library to the most up-to-date version, and the problem persists.

**Comment by gladkia** [comment]
Hi @heimannch.

1. I've tested the demo app and `hg19` seems to work fine with the demo app.
<img width="600" alt="igvShiny_hg19" src="https://github.com/user-attachments/assets/7cda0e71-8d45-47fc-9dbf-58e36e4653d5">

2. Does this demo app work fine for you?
```
demo_app_file <- system.file(package = "igvShiny", "demos", "groupAutoScale.R")
shiny::runApp(demo_app_file)
```
3. Do you use the latest version (1.05) from the master branch?

**Comment by gladkia** [comment]
@heimannch please attach `sessionInfo`. 

Also please rerun the demo app and provide me with the js logs. You can use the DevTools (instructions for Firefox: https://firefox-source-docs.mozilla.org/devtools-user/). 

For reference, here are the js logs from my browser:
<img width="1790" alt="js_logs_igvShiny_demo_app" src="https://github.com/user-attachments/assets/e6300f63-53e4-4bd8-8484-dd5179fd209a">

**Comment by heimannch** [comment]
Thanks for the reply, @gladkia.
As I was gathering the required information, I've noticed that both locally and in the deployed app (https://isb-cgc.shinyapps.io/iatlas/?module=germline) the situation is solved. I haven't made any changes, so that was surprising - did you make any updates, or do you want me to send you the logs and/or keep monitoring the situation? Thanks!

**Comment by gladkia** [comment]
@heimannch thanks for the info. 
No, I did not make any changes. 
I'm closing this issue then.
